name: Auto Update goida-vpn-configs

on:
  schedule:
    - cron: '17 * * * *'     # каждый час в 17-ю минуту (меньше задержек)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.MY_TOKEN }}
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('source/requirements.txt') }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd source && pip install --no-cache-dir -r requirements.txt

      - name: Run main.py
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: cd source && python main.py
